name: Smoke Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  syntax-test:
    runs-on: ubuntu-latest
    name: Syntax Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 2
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"

  smoke-test-default:
    runs-on: ubuntu-latest
    name: Smoke Test Default
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 0
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"

  smoke-test-exclude-glob:
    runs-on: ubuntu-latest
    name: Smoke Test Exclude Glob
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          glob: examples/spec/**/*_spec.rb
          exclude-glob: examples/spec/**/t*_spec.rb
          split-total: 1
          split-index: 0
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"
      - run: |
          if echo "${{ steps.split-tests.outputs.test-suite }}" | grep -q '/token_spec.rb'; then
            echo "/token_spec.rb is included in the test-suite, failing the job."
            exit 1
          else
            echo "token_spec.rb is not included in the test-suite, proceeding."
          fi
        name: Check for token_spec.rb

  smoke-test-line:
    runs-on: ubuntu-latest
    name: Smoke Test Line Count
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          line-count: true
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 1
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"

  smoke-test-junit:
    runs-on: ubuntu-latest
    name: Smoke Test JUnit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          junit-path: examples/
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 1
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"
